//
//  MainViewController.swift
//  worldlinetest
//
//  Created by Marcos Molero on 05/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import MapKit

protocol MainDisplayLogic: class {
    func displayPointsOI(viewModel: MainScene.GetPointsOI.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic {
    
    var interactor: MainBusinessLogic?
    var router: (MainRoutingLogic & MainDataPassing)?
    var dependencyInjector:SceneDependencyInjector! = MainDependencyInjector()
    
    // MARK: Object lifecycle
    @IBOutlet weak var mapView: MKMapView!
    
    var displayPointsOI: [MainScene.GetPointsOI.DisplayPointOI] = []
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        dependencyInjector.inject(to:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getPointsOI()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.isHidden = true
        setupMap()
    }
    
    // MARK: Requests
    func getPointsOI() {
        let request = MainScene.GetPointsOI.Request()
        interactor?.getPointsOI(request: request)
    }
    
    func savePointsOIToLocalDB(displayPointsOI: [MainScene.GetPointsOI.DisplayPointOI]) {
        var pointsOI: [PointOI] = []
        for item in displayPointsOI {
            let pointOI = PointOI(id: item.id, title: item.title, address: nil, transport: nil, email: nil, latitude: item.latitude, longitude: item.longitude, description: nil, phone: nil)
            pointsOI.append(pointOI)
        }
        
        let request = MainScene.SavePointsOIToLocalDB.Request(pointsOI: pointsOI)
        interactor?.savePointsOIToLocalDB(request: request)
    }
    
    // MARK: Display logic
    func displayPointsOI(viewModel: MainScene.GetPointsOI.ViewModel) {
        self.displayPointsOI = viewModel.displayPointsOI
        savePointsOIToLocalDB(displayPointsOI: viewModel.displayPointsOI)
        displayOnMap()
    }
}

extension MainViewController {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
