//
//  MainModels.swift
//  worldlinetest
//
//  Created by Marcos Molero on 05/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import MapKit

enum MainScene {
    enum GetPointsOI {
        
        struct Request {
            
        }
        
        struct Response {
            let pointsOI: [PointOI]
        }
        
        struct ViewModel {
            let displayPointsOI: [DisplayPointOI]
        }
        
        struct DisplayPointOI {
            let id: String
            let title: String
            let latitude: String
            let longitude: String
        }
    }
    
    enum SavePointsOIToLocalDB {
        
        struct Request {
            let pointsOI: [PointOI]
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum SavePointOIToDataStore {
        
        struct Request {
            let pointOI: PointOI
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
}
