//
//  MainInteractor.swift
//  worldlinetest
//
//  Created by Marcos Molero on 05/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MainBusinessLogic {
    func getPointsOI(request: MainScene.GetPointsOI.Request)
}

protocol MainDataStore {
    
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    
    var presenter: MainPresentationLogic?
    var pointOIStoreWorker: PointOIStoreWorker!
    
    // MARK: Business logic
    func getPointsOI(request: MainScene.GetPointsOI.Request) {
        pointOIStoreWorker.getPointsOI { (result) in
            switch result {
            case .success(let pointsOI):
                let response = MainScene.GetPointsOI.Response(pointsOI: pointsOI)
                self.presenter?.presentPointsOI(response: response)
                break
            case .failure(let error):
                debugPrint(error.localizedDescription)
                break
            }
        }
    }
}
