//
//  PointOIStoreWorker.swift
//  worldlinetest
//
//  Created by Marcos Molero on 05/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

class PointOIStoreWorker {
    // MARK: Business Logic
 
    let pointOIStores: [PointOIStore]!
    
    init(stores: [PointOIStore]) {
        self.pointOIStores = stores
    }
    
    func getPointsOI(completion: @escaping PointOIStoreGetPointsOICompletionHandler) {
        pointOIStores[0].getPointsOI(completion: completion)
    }

    func getPointOI(withId id: String, completion: @escaping PointOIStoreGetPointOICompletionHandler) {
        pointOIStores[0].getPointOI(withId: id, completion: completion)
    }
    
    func savePointsOI(with pointsOI: [PointOI], completion: @escaping PointOIStoreSavePointsOICompletionHandler) {
        pointOIStores[1].savePointsOI(with: pointsOI, completion: completion)
    }
    
    func updatePointOI(with pointOI: PointOI, completion: @escaping PointOIStoreUpdatePointOICompletionHandler) {
        pointOIStores[1].updatePointOI(with: pointOI, completion: completion)
    }
    
    func getPointsOIFromDB(completion: @escaping PointOIStoreGetPointsOIFromDBCompletionHandler) {
        pointOIStores[1].getPointsOIFromDB(completion: completion)
    }
}
