//
//  PointOIStoreWorker.swift
//  worldlinetest
//
//  Created by Marcos Molero on 05/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

class PointOIStoreWorker {
    // MARK: Business Logic
 
    let pointOIStore: PointOIStore!
    
    init(store: PointOIStore) {
        self.pointOIStore = store
    }
    
    func getPointsOI(completion: @escaping PointOIStoreGetPointsOICompletionHandler) {
        pointOIStore.getPointsOI(completion: completion)
    }

    func getPointOI(withId id: String, completion: @escaping PointOIStoreGetPointOICompletionHandler) {
        pointOIStore.getPointOI(withId: id, completion: completion)
    }
}
