//
//  LandingInteractor.swift
//  CleanArchitecture
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol LandingBusinessLogic {
    
}

protocol LandingDataStore {
    
}

class LandingInteractor: LandingBusinessLogic, LandingDataStore {
    
    var presenter: LandingPresentationLogic?
    
    // MARK: Business logic
    

}
