//
//  LandingPresenter.swift
//  CleanArchitecture
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol LandingPresentationLogic {
    
}

class LandingPresenter: LandingPresentationLogic {
    
    weak var viewController: LandingDisplayLogic?
    
    // MARK: Presentation logic
    
}
