//
//  LandingRouter.swift
//  CleanArchitecture
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

import UIKit

protocol LandingRoutingLogic {
    
}

protocol LandingDataPassing {
    func passDataToNextScene(for segue:UIStoryboardSegue)
    var dataStore: LandingDataStore? { get }
}

class LandingRouter: LandingRoutingLogic, LandingDataPassing {
    
    weak var viewController: LandingViewController?
    var dataStore: LandingDataStore?
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
