//
//  DetailModels.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

enum DetailScene {
    enum GetPointOIDetail {
        
        struct Request {
            
        }
        
        struct Response {
            let pointOI: PointOI
        }
        
        struct ViewModel {
            let displayPointOI: DisplayPointOI
        }
        
        struct DisplayPointOI {
            let title: String
            let address: String
            let transport: String
            let email: String
            let description: String
            let phone: String
        }
    }
    
    enum UpdatePointOI {
        
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    
}
