//
//  DetailInteractor.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol DetailBusinessLogic {
    func getPointOIDetail(request: DetailScene.GetPointOIDetail.Request)
    func updatePointOI(request: DetailScene.UpdatePointOI.Request)
}

protocol DetailDataStore {
    var pointOI: PointOI! { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    
    var presenter: DetailPresentationLogic?
    var pointOIStoreWorker: PointOIStoreWorker!
    var pointOI: PointOI!
    
    // MARK: Business logic
    func getPointOIDetail(request: DetailScene.GetPointOIDetail.Request) {
        pointOIStoreWorker.getPointOI(withId: pointOI.id) { (result) in
            switch result {
            case .success(let pointOI):
                self.pointOI = pointOI
                let response = DetailScene.GetPointOIDetail.Response(pointOI: pointOI)
                self.presenter?.presentPointOIDetail(response: response)
                break
            case .failure(let error):
                debugPrint(error.localizedDescription)
                break
            }
        }
    }
    
    func updatePointOI(request: DetailScene.UpdatePointOI.Request) {
        pointOIStoreWorker.updatePointOI(with: self.pointOI) { (result) in
            switch result {
            case .success:
                debugPrint("The item has been saved")
                break
            case .failure(let error):
                debugPrint(error.localizedDescription)
                break
            }
        }
    }

}
