//
//  DetailPresenter.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates

protocol DetailPresentationLogic {
    func presentPointOIDetail(response: DetailScene.GetPointOIDetail.Response)
}

class DetailPresenter: DetailPresentationLogic {
    
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Presentation logic
    func presentPointOIDetail(response: DetailScene.GetPointOIDetail.Response) {
        let viewModel = mapResponseToViewModel(response: response)
        viewController?.displayPointOI(viewModel: viewModel)
    }
    
    func mapResponseToViewModel(response: DetailScene.GetPointOIDetail.Response) -> DetailScene.GetPointOIDetail.ViewModel {
        let displayPointOI = mapPointOIToDisplayPointOI(pointOI: response.pointOI)
        return DetailScene.GetPointOIDetail.ViewModel(displayPointOI: displayPointOI)
    }
    
    func mapPointOIToDisplayPointOI(pointOI: PointOI) -> DetailScene.GetPointOIDetail.DisplayPointOI {
        let title = pointOI.title ?? "Title is not available"
        let address = pointOI.address ?? "Address is not available"
        var transport = pointOI.transport ?? "Transport is not available"
        if transport == "null" { transport = "Transport is not available" }
        var email = pointOI.email ?? "Email is not available"
        if !email.contains("@") { email = "Email is not available" }
        let description = pointOI.description ?? "Description is not available"
        let phone = pointOI.phone ?? "Phone is not available"
        
        return DetailScene.GetPointOIDetail.DisplayPointOI(title: title, address: address, transport: transport, email: email, description: description, phone: phone)
    }
}
