//
//  SearchInteractor.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SearchBusinessLogic {
    func getPointsOIFromDB(request: SearchScene.GetPointsOIFromDB.Request)
}

protocol SearchDataStore {
    
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    
    var presenter: SearchPresentationLogic?
    var pointOIStoreWorker: PointOIStoreWorker!
    
    // MARK: Business logic
    func getPointsOIFromDB(request: SearchScene.GetPointsOIFromDB.Request) {
        pointOIStoreWorker.getPointsOIFromDB { (result) in
            switch result {
            case .success(let pointsOI):
                let response = SearchScene.GetPointsOIFromDB.Response(pointsOI: pointsOI)
                self.presenter?.presentPointsOIFromDB(response: response)
                break
            case .failure(let error):
                debugPrint(error.localizedDescription)
                break
            }
        }
    }

}
