//
//  SearchDependencyInjector.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import Swinject

// MARK: Inject all scene dependencies

class SearchDependencyInjector: SwinjectViewControllerDependencyInjector<SearchViewController> {
    
    // MARK: Registration
    
    override class func registerDependencies(container: Container) {
        container.register(SearchViewController.self) { (resolver, viewController:SearchViewController) -> SearchViewController in
            let interactor = resolver.resolve(SearchInteractor.self)!
            let presenter = SearchPresenter()
            let router = SearchRouter()
            viewController.interactor = interactor
            viewController.router = router
            interactor.presenter = presenter
            presenter.viewController = viewController
            router.viewController = viewController
            router.dataStore = interactor
            return viewController
        }
    }
}
