//
//  SearchModels.swift
//  worldlinetest
//
//  Created by Marcos Molero on 07/11/2018.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

enum SearchScene {
    enum GetPointsOIFromDB {
        
        struct Request {
            
        }
        
        struct Response {
            let pointsOI: [PointOI]
        }
        
        struct ViewModel {
            let displayPointsOI: [DisplayPointOI]
        }
        
        struct DisplayPointOI {
            let id: String
            let title: String
        }
    }
}
